on:
  release:
    types: [created]

name: Deploy Valkyrie

jobs:
  deploy:
    name: Deploy Valkyrie
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: setup python
      uses: actions/setup-python@v2
    
    - name: Install boto3
      run: |
          python -m pip install --upgrade pip
          pip install boto3
    
    - name: Run updater
      run: |
        python deploy_valkyrie.py
      env:
        aws-deploy-bucket: ${{ secrets.DEPLOY_BUCKET }}
        aws-access-key: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1
